const RANDCODE_USERNAME = 'ZSZM005389'
const RANDCODE_PASSWORD = '123456'

const SERVER_ADDRESS = 'https://api.sa9051.top'

module.exports = {
  RANDCODE_USERNAME: RANDCODE_USERNAME,
  RANDCODE_PASSWORD: RANDCODE_PASSWORD,
  SERVER_ADDRESS: SERVER_ADDRESS
}